# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1192bd67974255fd95e61dc1bc741239a2087672d7034b456db2490f4c1433d21954bbe5767bad7f7892d6c205fbc37f5919eb5ae118248b8534bcc1177023a3

test:
  secret_key_base: cef82b853e1de14031f8c44589d09754353ed56ca72d0543cf6631157b9983fe53ee60da32b70543d4c773788b950cd665863e8d2a1e9a49b54c6f34878c03c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
